name: Sync Obsidian to Drive

on:
  push:
    paths:
      - 'Assets/Documentação/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rclone
        run: sudo apt-get install -y rclone

      - name: Create Rclone Config
        run: |
          mkdir -p ~/.config/rclone
          echo "[gdrive]" > ~/.config/rclone/rclone.conf
          echo "type = drive" >> ~/.config/rclone/rclone.conf
          echo "scope = drive" >> ~/.config/rclone/rclone.conf
          echo "service_account_contents = ${{ secrets.GDRIVE_CREDENTIALS_JSON }}" >> ~/.config/rclone/rclone.conf

      - name: Sync Folder to Drive
        run: |
          # O parâmetro --drive-root-folder-id garante que ele vá direto para a pasta certa
          rclone sync ./Assets/Documentação gdrive: --drive-root-folder-id ${{ secrets.GDRIVE_FOLDER_ID }} -v
