name: Sync Obsidian Individual Files

on:
  push:
    paths:
      - 'Assets/Documentação/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Passo de debug: Lista os arquivos para garantir que o caminho está certo
      - name: List files for debug
        run: |
          echo "Verificando arquivos na pasta Documentação:"
          ls -R Assets/Documentação

      - name: Upload to Google Drive
        uses: skick1234/google-drive-upload-git-action@master
        with:
          # Use o segredo em BASE64 (gerado no PowerShell)
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          # Caminho da pasta de origem
          filename: 'Assets/Documentação'
          overwrite: "true"
          # Mantém a estrutura de pastas para o seu professor
          recursive: "true"
