name: Upload Obsidian Vault to Drive

on:
  push:
    paths:
      - 'Assets/Documentação/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Atualizado para v4 (mais recente)

      - name: Zip Documentation Folder
        run: |
          zip -r documentacao_backup.zip "Assets/Documentação/"
          # O comando acima cria o arquivo documentacao_backup.zip
          # contendo tudo dentro do caminho especificado.

      - name: Upload Zip to Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: 'documentacao_backup.zip' # Enviamos o arquivo zip gerado
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: "true"
